---
role_name_check: 1
driver:
  name: podman
platforms:
  - name: lidarr_latest
    image: quay.io/speakintelnet/pinp-molecule
    privileged: true
    pre_build_image: true
    systemd: true
  - name: lidarr_develop
    image: quay.io/speakintelnet/pinp-molecule
    privileged: true
    pre_build_image: true
    systemd: true
  - name: lidarr_nightly
    image: quay.io/speakintelnet/pinp-molecule
    privileged: true
    pre_build_image: true
    systemd: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      lidarr_latest:
        ansible_user: podman
        lidarr_version: latest
      lidarr_develop:
        ansible_user: podman
        lidarr_version: develop
      lidarr_nightly:
        ansible_user: podman
        lidarr_version: nightly
verifier:
  name: ansible
